version: '3'
services:
    mongodb:
        image: mongo:latest
        container_name: appleshop_mongo
        ports:
            - '27017:27017'
        environment:
            - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
            - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
            - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
        volumes:
            - mongo_data:/data/db
    redis:
        image: redis:latest
        container_name: appleshop_redis
        ports:
            - '6379:6379'
        volumes:
            - redis_data:/data
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.10.0
        container_name: appleshop_es
        environment:
            - node.name=appleshop_es
            - cluster.name=docker-cluster
            - bootstrap.memory_lock=true
            - discovery.type=single-node
        ports:
            - '9200:9200'
        ulimits:
            memlock:
                soft: -1
                hard: -1
        volumes:
            - esdata:/usr/share/elasticsearch/data
    kibana:
        image: docker.elastic.co/kibana/kibana:7.10.0
        container_name: appleshop_kibana
        ports:
            - 5601:5601
        depends_on:
            - elasticsearch
    rabbitmq:
        image: rabbitmq:3-management-alpine
        container_name: rabbitmq
        ports:
            - 5672:5672
            - 15672:15672
        volumes:
            - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
            - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    backend:
        build: .
        container_name: backend_container
        ports:
            - '8000:8000'
        volumes:
            - ./backend-nodejs:/usr/src/app # Gắn toàn bộ thư mục mã nguồn vào container
            - /usr/src/app/node_modules # Volume ẩn danh để tránh ghi đè node_modules
        depends_on:
            - mongodb
            - elasticsearch
            - redis
volumes:
    mongo_data:
        driver: local # Volume cho MongoDB
    esdata:
        driver: local # Volume cho Elasticsearch
    redis_data:
        driver: local
    rabbitmq:
        driver: local
