const TYPE_NOTIFICATION = {
    ORDER_SUCCESS: 'ORDER SUCCESSFULLY',
    ORDER_FAIL: 'ORDER FAILED',
    ORDER_PENDING: 'ORDER PENDING',
    ORDER_CONFIRMED: 'ORDER CONFIRM',
    ORDER_SHIPPED: 'ORDER SHIPPED',
    ORDER_CANCELLED: 'ORDER CANCELLED',
    PROMOTION_NEW: 'NEW PROMOTION',
    PROMOTION_EXPIRE: 'EXPIRED PROMOTION'
};
const STOCK_STATUS = {
    OUT_OF_STOCK: 'OUT OF STOCK',
    LOW_INVENTORY: 'LOW INVENTORY',
    IN_STOCK: 'IN_STOCK',
};

const PRODUCT_STATUS = {
    ALL: 'ALL',
    DELETED: 'DELETED',
    DRAFT: 'DRAFT',
    PUBLISHED: 'PUBLISHED',
};
const DISCOUNT_TYPE = {
    PERCENTAGE: "percenage",
    FIXED: "fixed"
}
const SEND_NOTIFICATION_TYPE = {
    BROADCAST: 'BROADCAST',
    INDIVIDUAL: 'INDIIDUAL'
}
export {
    TYPE_NOTIFICATION,
    STOCK_STATUS,
    PRODUCT_STATUS,
    DISCOUNT_TYPE,
    SEND_NOTIFICATION_TYPE
};